version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "das-processing-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cz9pimk1ldme"
s3_prefix = "das-processing-lambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DasKinesisStream=\"O2YLDATTX3P62JYYEOP4IT27MI \" DasS3Bucket=\"944963212507-das-bucket\" DasS3Prefix=\"das\" AccessKeyIDUniqueString=\"3oqLQE\" SecretAccessKeyUniqueString=\"z1hqI6\""
image_repositories = []
