AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/java-events-1.0-SNAPSHOT.jar
      Handler: example.HandlerAuroraStream
      Runtime: java11
      Description: Java function
      Environment:
        Variables:
          DATABASE_TYPE: postgres
          DYNAMO_DB_TABLE: !Ref AuroraStreamDynamoDBTable
          KINESIS_FIREHOSE_STREAM: LambdaToOpenSearch
          S3_BUCKET: lambda-to-s3-3051-3131-6250
          S3_PREFIX: das
      MemorySize: 512
      Timeout: 30
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonKinesisFirehoseFullAccess
        - AmazonS3FullAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref AuroraStreamDynamoDBTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aws-access-key-id-sMqvoA"
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aws-secret-access-key-2FnHYk"        
      Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/aws-rds-das-cluster-EJFKQ5RQN6YEYEIQGPTH5Z4TRY"
            BatchSize: 10
            StartingPosition: LATEST
  AuroraStreamDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: AuroraStreamsMaven
      PrimaryKey:
        Name: CorrelationId
        Type: String